name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode 13.2.1
      run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
    - name: Pod Install
      run: pod install
    - name: Build App
      run: xcodebuild -workspace 'Supertal Practical.xcworkspace' -scheme 'Supertal Practical' -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest'
